name: Build and Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:lts-alpine3.12
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:13
        env:
          POSTGRES_USER: drugs
          POSTGRES_PASSWORD: drugs
          POSTGRES_DB: drugs
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Initialize testing database
        run: node "$GITHUB_WORKSPACE"/src/__tests__/db/init-db.js
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: drugs
     
