name: Build and Test
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ['14.x', '16.x']
    name: Node ${{ matrix.node-version }} / ${{ matrix.db-type }}
    env:
      TEST_DB_TYPE: pg
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: drugs
          POSTGRES_USER: drugs
          POSTGRES_PASSWORD: drugs
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout project repository
        uses: actions/checkout@v2
      - name: Initialize testing database
        run: |
          cd "$GITHUB_WORKSPACE"/src/__tests__/db/pg
          psql "$CONNSTR" -a -q -f sql/create-schema.sql
          psql "$CONNSTR" -a -q -f sql/create-schema-objects.sql
          psql "$CONNSTR" -a -q -f sql/create-test-data.sql
        env:
          CONNSTR: "postgresql://drugs:drugs@localhost:5432/drugs"
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install global npm dependencies
        run: npm i -g rimraf mkdirp typescript-json-schema jest
      - name: Install project npm dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Set up JDK 11 for Java tests
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run project tests
        run: npm test
        env:
          PGHOST: localhost
          PGPORT: 5432
          PGDATABASE: drugs
          PGUSER: drugs
          PGPASSWORD: drugs
